
import Girl1 from "../../../public/girl1.jpg"
import Girl2 from "../../../public/girl2.jpg"
import Girl3 from "../../../public/girl3.jpg"
import Girl4 from "../../../public/girl4.jpg"
import Girl5 from "../../../public/girl5.jpg"
import Girl6 from "../../../public/girl6.jpg"


import MyToyotawhite1 from "../../../public/Toyotawhite1.jpg"
import MyToyotawhite2 from "../../../public/Toyotawhite2.jpg"
import MyToyotawhite3 from "../../../public/Toyotawhite3.jpg"
import MyToyotawhite4 from "../../../public/Toyotawhite4.jpg"

import RedKiaSoul1 from "../../../public/RedKiasoul1.jpg"
import RedKiaSoul2 from "../../../public/RedKiasoul2.jpg"
import RedKiaSoul3 from "../../../public/RedKiasoul3.jpg"
import RedKiaSoul4 from "../../../public/RedKiasoul4.jpg"

import Card3 from "../../../public/card3.jpg"
import Card4 from "../../../public/card4.jpg"
import Card5 from "../../../public/card5.jpg"

import ToyoTablue1 from "../../../public/Toyotablue1.jpg"
import ToyoTablue2 from "../../../public/Toyotablue2.jpg"
import ToyoTablue3 from "../../../public/Toyotablue3.jpg"
import ToyoTablue4 from "../../../public/Toyotablue4.jpg"

import Ford1 from "../../../public/Ford1.jpg"
import Ford2 from "../../../public/Ford2.jpg"
import Ford3 from "../../../public/Ford3.jpg"
import Ford4 from "../../../public/Ford4.jpg"

import Chevrolet2 from "../../../public/Chevrolet2.jpg"
import Chevrolet1 from "../../../public/Chevrolet1.jpg"
import Chevrolet3 from "../../../public/Chevrolet3.jpg"
import Chevrolet4 from "../../../public/Chevrolet4.jpg"



const Productdata = [
{
category: "Toyota",
productonimg:"Toyota",
productname: " my Toyota Camry SE 350",
productviews: "(4.0) 138 Reviews",
productlocationpin: "3.2m",
producttype:"Auto",
productspeed:"10 KM",
producttank:"Petrol",
productsystem:"Power",
productyear:2018,
productcity:"Washington",
productprice: '$160',
productimg1:MyToyotawhite1 ,
productimg2:MyToyotawhite2  ,
productimg3:MyToyotawhite3  ,
productimg4:MyToyotawhite4  ,
productimg0:Girl1

},
{
    category: "Toyota",
    productonimg:"Toyota",
    productname: "aaa Toyota Camry SE 350",
    productviews: "(4.0) 138 Reviews",
    productlocationpin: "3.2m",
    producttype:"Auto",
    productspeed:"10 KM",
    producttank:"Petrol",
    productsystem:"Power",
    productyear:2018,
    productcity:"Washington",
    productprice: '$160',
    productimg1: RedKiaSoul1 ,
    productimg2: RedKiaSoul2  ,
    productimg3: RedKiaSoul3  ,
    productimg4: RedKiaSoul4  ,
    productimg0:Girl2
    },
    {
        category: "Toyota",
        productonimg:"Toyota",
        productname: "Toyota Camry SE 350",
        productviews: "(4.0) 138 Reviews",
        productlocationpin: "3.2m",
        producttype:"Auto",
        productspeed:"10 KM",
        producttank:"Petrol",
        productsystem:"Power",
        productyear:2018,
        productcity:"Washington",
        productprice: '$160',
        productimg1:MyToyotawhite1  ,
        productimg2:MyToyotawhite2  ,
        productimg3:MyToyotawhite3  ,
        productimg4:MyToyotawhite4  ,
        productimg0:Girl3
        },
        {
            category: "Toyota",
            productonimg:"Toyota",
            productname: "Toyota Camry SE 350",
            productviews: "(4.0) 138 Reviews",
            productlocationpin: "3.2m",
            producttype:"Auto",
            productspeed:"10 KM",
            producttank:"Petrol",
            productsystem:"Power",
            productyear:2018,
            productcity:"Washington",
            productprice: '$160',
            productimg1:Card3  ,
            productimg2:Card3  ,
            productimg3:Card3 ,
            productimg4:Card3 ,
            productimg0:Girl4
            },
            {
                category: "Toyota",
                productonimg:"Toyota",
                productname: "Toyota Camry SE 350",
                productviews: "(4.0) 138 Reviews",
                productlocationpin: "3.2m",
                producttype:"Auto",
                productspeed:"10 KM",
                producttank:"Petrol",
                productsystem:"Power",
                productyear:2018,
                productcity:"Washington",
                productprice: '$160',
                productimg1:Card4  ,
                productimg2:Card4   ,
                productimg3:Card4   ,
                productimg4:Card4   ,
                productimg0:Girl5
                },
                {
                    category: "Toyota",
                    productonimg:"Toyota",
                    productname: "Toyota Camry SE 350",
                    productviews: "(4.0) 138 Reviews",
                    productlocationpin: "3.2m",
                    producttype:"Auto",
                    productspeed:"10 KM",
                    producttank:"Petrol",
                    productsystem:"Power",
                    productyear:2018,
                    productcity:"Washington",
                    productprice: '$160',
                    productimg1:Card5   ,
                    productimg2:Card5   ,
                    productimg3:Card5  ,
                    productimg4:Card5  ,
                    productimg0:Girl6
                    },

                    {
                        category: "Toyota",
                        productonimg:"Toyota",
                        productname: "Toyota Camry SE 350",
                        productviews: "(4.0) 138 Reviews",
                        productlocationpin: "3.2m",
                        producttype:"Auto",
                        productspeed:"10 KM",
                        producttank:"Petrol",
                        productsystem:"Power",
                        productyear:2018,
                        productcity:"Washington",
                        productprice: '$160',
                        productimg1:ToyoTablue1  ,
                        productimg2:ToyoTablue2   ,
                        productimg3:ToyoTablue3  ,
                        productimg4:ToyoTablue4 ,
                        productimg0:Girl1
                        },
                         {
                            category: "Toyota",
                            productonimg:"Toyota",
                            productname: "Toyota Camry SE 350",
                            productviews: "(4.0) 138 Reviews",
                            productlocationpin: "3.2m",
                            producttype:"Auto",
                            productspeed:"10 KM",
                            producttank:"Petrol",
                            productsystem:"Power",
                            productyear:2018,
                            productcity:"Washington",
                            productprice: '$160',
                            productimg1:Ford1   ,
                            productimg2:Ford2  ,
                            productimg3:Ford3  ,
                            productimg4:Ford4  ,
                            productimg0:Girl6
                            },
                             {
                                category: "Toyota",
                                productonimg:"Toyota",
                                productname: "Toyota Camry SE 350",
                                productviews: "(4.0) 138 Reviews",
                                productlocationpin: "3.2m",
                                producttype:"Auto",
                                productspeed:"10 KM",
                                producttank:"Petrol",
                                productsystem:"Power",
                                productyear:2018,
                                productcity:"Washington",
                                productprice: '$160',
                                productimg1: Chevrolet2    ,
                                productimg2: Chevrolet1  ,
                                productimg3: Chevrolet3  ,
                                productimg4: Chevrolet4  ,
                                productimg0:Girl6
                                },
                                // 

                                {
            category: "Audi",
            productonimg:"Audi",
            productname: "Audi Camry SE 350",
            productviews: "(4.0) 138 Reviews",
            productlocationpin: "3.2m",
            producttype:"Auto",
            productspeed:"10 KM",
            producttank:"Petrol",
            productsystem:"Power",
            productyear:2018,
            productcity:"Washington",
            productprice: '$160',
            productimg1:MyToyotawhite1 ,
            productimg2:MyToyotawhite2  ,
            productimg3:MyToyotawhite3  ,
            productimg4:MyToyotawhite4  ,
            productimg0:Girl1
            
            },
            {
                category: "Audi",
                productonimg:"Audi",
                productname: "Audi Camry SE 350",
                productviews: "(4.0) 138 Reviews",
                productlocationpin: "3.2m",
                producttype:"Auto",
                productspeed:"10 KM",
                producttank:"Petrol",
                productsystem:"Power",
                productyear:2018,
                productcity:"Washington",
                productprice: '$160',
                productimg1: RedKiaSoul1 ,
                productimg2: RedKiaSoul2  ,
                productimg3: RedKiaSoul3  ,
                productimg4: RedKiaSoul4  ,
                productimg0:Girl2
                },
                {
                    category: "Audi",
                    productonimg:"Audi",
                    productname: "Audi Camry SE 350",
                    productviews: "(4.0) 138 Reviews",
                    productlocationpin: "3.2m",
                    producttype:"Auto",
                    productspeed:"10 KM",
                    producttank:"Petrol",
                    productsystem:"Power",
                    productyear:2018,
                    productcity:"Washington",
                    productprice: '$160',
                    productimg1:MyToyotawhite1  ,
                    productimg2:MyToyotawhite2  ,
                    productimg3:MyToyotawhite3  ,
                    productimg4:MyToyotawhite4  ,
                    productimg0:Girl3
                    },
                    {
                        category: "Audi",
                        productonimg:"Audi",
                        productname: "Audi Camry SE 350",
                        productviews: "(4.0) 138 Reviews",
                        productlocationpin: "3.2m",
                        producttype:"Auto",
                        productspeed:"10 KM",
                        producttank:"Petrol",
                        productsystem:"Power",
                        productyear:2018,
                        productcity:"Washington",
                        productprice: '$160',
                        productimg1:Card3  ,
                        productimg2:Card3  ,
                        productimg3:Card3 ,
                        productimg4:Card3 ,
                        productimg0:Girl4
                        },
                        {
                            category: "Audi",
                            productonimg:"Audi",
                            productname: "Audi Camry SE 350",
                            productviews: "(4.0) 138 Reviews",
                            productlocationpin: "3.2m",
                            producttype:"Auto",
                            productspeed:"10 KM",
                            producttank:"Petrol",
                            productsystem:"Power",
                            productyear:2018,
                            productcity:"Washington",
                            productprice: '$160',
                            productimg1:Card4  ,
                            productimg2:Card4   ,
                            productimg3:Card4   ,
                            productimg4:Card4   ,
                            productimg0:Girl5
                            },
                            {
                                category: "Audi",
                                productonimg:"Audi",
                                productname: "Audi Camry SE 350",
                                productviews: "(4.0) 138 Reviews",
                                productlocationpin: "3.2m",
                                producttype:"Auto",
                                productspeed:"10 KM",
                                producttank:"Petrol",
                                productsystem:"Power",
                                productyear:2018,
                                productcity:"Washington",
                                productprice: '$160',
                                productimg1:Card5   ,
                                productimg2:Card5   ,
                                productimg3:Card5  ,
                                productimg4:Card5  ,
                                productimg0:Girl6
                                },
            
                                {
                                    category: "Audi",
                                    productonimg:"Audi",
                                    productname: "Audi Camry SE 350",
                                    productviews: "(4.0) 138 Reviews",
                                    productlocationpin: "3.2m",
                                    producttype:"Auto",
                                    productspeed:"10 KM",
                                    producttank:"Petrol",
                                    productsystem:"Power",
                                    productyear:2018,
                                    productcity:"Washington",
                                    productprice: '$160',
                                    productimg1:ToyoTablue1  ,
                                    productimg2:ToyoTablue2   ,
                                    productimg3:ToyoTablue3  ,
                                    productimg4:ToyoTablue4 ,
                                    productimg0:Girl1
                                    },
                                     {
                                        category: "Audi",
                                        productonimg:"Audi",
                                        productname: "Audi Camry SE 350",
                                        productviews: "(4.0) 138 Reviews",
                                        productlocationpin: "3.2m",
                                        producttype:"Auto",
                                        productspeed:"10 KM",
                                        producttank:"Petrol",
                                        productsystem:"Power",
                                        productyear:2018,
                                        productcity:"Washington",
                                        productprice: '$160',
                                        productimg1:Ford1   ,
                                        productimg2:Ford2  ,
                                        productimg3:Ford3  ,
                                        productimg4:Ford4  ,
                                        productimg0:Girl6
                                        },
                                         {
                                            category: "Audi",
                                            productonimg:"Audi",
                                            productname: "Audi Camry SE 350",
                                            productviews: "(4.0) 138 Reviews",
                                            productlocationpin: "3.2m",
                                            producttype:"Auto",
                                            productspeed:"10 KM",
                                            producttank:"Petrol",
                                            productsystem:"Power",
                                            productyear:2018,
                                            productcity:"Washington",
                                            productprice: '$160',
                                            productimg1: Chevrolet2    ,
                                            productimg2: Chevrolet1  ,
                                            productimg3: Chevrolet3  ,
                                            productimg4: Chevrolet4  ,
                                            productimg0:Girl6
                                            },
                                            
                                // 

                                {
            category: "Honda",
            productonimg:"Honda",
            productname: "Honda Camry SE 350",
            productviews: "(4.0) 138 Reviews",
            productlocationpin: "3.2m",
            producttype:"Auto",
            productspeed:"10 KM",
            producttank:"Petrol",
            productsystem:"Power",
            productyear:2018,
            productcity:"Washington",
            productprice: '$160',
            productimg1:MyToyotawhite1 ,
            productimg2:MyToyotawhite2  ,
            productimg3:MyToyotawhite3  ,
            productimg4:MyToyotawhite4  ,
            productimg0:Girl1
            
            },
            {
                category: "Honda",
                productonimg:"Honda",
                productname: "Honda Camry SE 350",
                productviews: "(4.0) 138 Reviews",
                productlocationpin: "3.2m",
                producttype:"Auto",
                productspeed:"10 KM",
                producttank:"Petrol",
                productsystem:"Power",
                productyear:2018,
                productcity:"Washington",
                productprice: '$160',
                productimg1: RedKiaSoul1 ,
                productimg2: RedKiaSoul2  ,
                productimg3: RedKiaSoul3  ,
                productimg4: RedKiaSoul4  ,
                productimg0:Girl2
                },
                {
                    category: "Honda",
                    productonimg:"Honda",
                    productname: "Honda Camry SE 350",
                    productviews: "(4.0) 138 Reviews",
                    productlocationpin: "3.2m",
                    producttype:"Auto",
                    productspeed:"10 KM",
                    producttank:"Petrol",
                    productsystem:"Power",
                    productyear:2018,
                    productcity:"Washington",
                    productprice: '$160',
                    productimg1:MyToyotawhite1  ,
                    productimg2:MyToyotawhite2  ,
                    productimg3:MyToyotawhite3  ,
                    productimg4:MyToyotawhite4  ,
                    productimg0:Girl3
                    },
                    {
                        category: "Honda",
                        productonimg:"Honda",
                        productname: "Honda Camry SE 350",
                        productviews: "(4.0) 138 Reviews",
                        productlocationpin: "3.2m",
                        producttype:"Auto",
                        productspeed:"10 KM",
                        producttank:"Petrol",
                        productsystem:"Power",
                        productyear:2018,
                        productcity:"Washington",
                        productprice: '$160',
                        productimg1:Card3  ,
                        productimg2:Card3  ,
                        productimg3:Card3 ,
                        productimg4:Card3 ,
                        productimg0:Girl4
                        },
                        {
                            category: "Honda",
                            productonimg:"Honda",
                            productname: "Honda Camry SE 350",
                            productviews: "(4.0) 138 Reviews",
                            productlocationpin: "3.2m",
                            producttype:"Auto",
                            productspeed:"10 KM",
                            producttank:"Petrol",
                            productsystem:"Power",
                            productyear:2018,
                            productcity:"Washington",
                            productprice: '$160',
                            productimg1:Card4  ,
                            productimg2:Card4   ,
                            productimg3:Card4   ,
                            productimg4:Card4   ,
                            productimg0:Girl5
                            },
                            {
                                category: "Honda",
                                productonimg:"Honda",
                                productname: "Honda Camry SE 350",
                                productviews: "(4.0) 138 Reviews",
                                productlocationpin: "3.2m",
                                producttype:"Auto",
                                productspeed:"10 KM",
                                producttank:"Petrol",
                                productsystem:"Power",
                                productyear:2018,
                                productcity:"Washington",
                                productprice: '$160',
                                productimg1:Card5   ,
                                productimg2:Card5   ,
                                productimg3:Card5  ,
                                productimg4:Card5  ,
                                productimg0:Girl6
                                },
            
                                {
                                    category: "Honda",
                                    productonimg:"Honda",
                                    productname: "Honda Camry SE 350",
                                    productviews: "(4.0) 138 Reviews",
                                    productlocationpin: "3.2m",
                                    producttype:"Auto",
                                    productspeed:"10 KM",
                                    producttank:"Petrol",
                                    productsystem:"Power",
                                    productyear:2018,
                                    productcity:"Washington",
                                    productprice: '$160',
                                    productimg1:ToyoTablue1  ,
                                    productimg2:ToyoTablue2   ,
                                    productimg3:ToyoTablue3  ,
                                    productimg4:ToyoTablue4 ,
                                    productimg0:Girl1
                                    },
                                     {
                                        category: "Honda",
                                        productonimg:"Honda",
                                        productname: "Honda Camry SE 350",
                                        productviews: "(4.0) 138 Reviews",
                                        productlocationpin: "3.2m",
                                        producttype:"Auto",
                                        productspeed:"10 KM",
                                        producttank:"Petrol",
                                        productsystem:"Power",
                                        productyear:2018,
                                        productcity:"Washington",
                                        productprice: '$160',
                                        productimg1:Ford1   ,
                                        productimg2:Ford2  ,
                                        productimg3:Ford3  ,
                                        productimg4:Ford4  ,
                                        productimg0:Girl6
                                        },
                                         {
                                            category: "Honda",
                                            productonimg:"Honda",
                                            productname: "Honda Camry SE 350",
                                            productviews: "(4.0) 138 Reviews",
                                            productlocationpin: "3.2m",
                                            producttype:"Auto",
                                            productspeed:"10 KM",
                                            producttank:"Petrol",
                                            productsystem:"Power",
                                            productyear:2018,
                                            productcity:"Washington",
                                            productprice: '$160',
                                            productimg1: Chevrolet2    ,
                                            productimg2: Chevrolet1  ,
                                            productimg3: Chevrolet3  ,
                                            productimg4: Chevrolet4  ,
                                            productimg0:Girl6
                                            } ,
                                           
                                           
                                            
                                            // 
            
                                            {
                        category: "Tesla",
                        productonimg:"Tesla",
                        productname: "Tesla Camry SE 350",
                        productviews: "(4.0) 138 Reviews",
                        productlocationpin: "3.2m",
                        producttype:"Auto",
                        productspeed:"10 KM",
                        producttank:"Petrol",
                        productsystem:"Power",
                        productyear:2018,
                        productcity:"Washington",
                        productprice: '$160',
                        productimg1:MyToyotawhite1 ,
                        productimg2:MyToyotawhite2  ,
                        productimg3:MyToyotawhite3  ,
                        productimg4:MyToyotawhite4  ,
                        productimg0:Girl1
                        
                        },
                        {
                            category: "Tesla",
                            productonimg:"Tesla",
                            productname: "Tesla Camry SE 350",
                            productviews: "(4.0) 138 Reviews",
                            productlocationpin: "3.2m",
                            producttype:"Auto",
                            productspeed:"10 KM",
                            producttank:"Petrol",
                            productsystem:"Power",
                            productyear:2018,
                            productcity:"Washington",
                            productprice: '$160',
                            productimg1: RedKiaSoul1 ,
                            productimg2: RedKiaSoul2  ,
                            productimg3: RedKiaSoul3  ,
                            productimg4: RedKiaSoul4  ,
                            productimg0:Girl2
                            },
                            {
                                category: "Tesla",
                                productonimg:"Tesla",
                                productname: "Tesla Camry SE 350",
                                productviews: "(4.0) 138 Reviews",
                                productlocationpin: "3.2m",
                                producttype:"Auto",
                                productspeed:"10 KM",
                                producttank:"Petrol",
                                productsystem:"Power",
                                productyear:2018,
                                productcity:"Washington",
                                productprice: '$160',
                                productimg1:MyToyotawhite1  ,
                                productimg2:MyToyotawhite2  ,
                                productimg3:MyToyotawhite3  ,
                                productimg4:MyToyotawhite4  ,
                                productimg0:Girl3
                                },
                                {
                                    category: "Tesla",
                                    productonimg:"Tesla",
                                    productname: "Tesla Camry SE 350",
                                    productviews: "(4.0) 138 Reviews",
                                    productlocationpin: "3.2m",
                                    producttype:"Auto",
                                    productspeed:"10 KM",
                                    producttank:"Petrol",
                                    productsystem:"Power",
                                    productyear:2018,
                                    productcity:"Washington",
                                    productprice: '$160',
                                    productimg1:Card3  ,
                                    productimg2:Card3  ,
                                    productimg3:Card3 ,
                                    productimg4:Card3 ,
                                    productimg0:Girl4
                                    },
                                    {
                                        category: "Tesla",
                                        productonimg:"Tesla",
                                        productname: "Tesla Camry SE 350",
                                        productviews: "(4.0) 138 Reviews",
                                        productlocationpin: "3.2m",
                                        producttype:"Auto",
                                        productspeed:"10 KM",
                                        producttank:"Petrol",
                                        productsystem:"Power",
                                        productyear:2018,
                                        productcity:"Washington",
                                        productprice: '$160',
                                        productimg1:Card4  ,
                                        productimg2:Card4   ,
                                        productimg3:Card4   ,
                                        productimg4:Card4   ,
                                        productimg0:Girl5
                                        },
                                        {
                                            category: "Tesla",
                                            productonimg:"Tesla",
                                            productname: "Tesla Camry SE 350",
                                            productviews: "(4.0) 138 Reviews",
                                            productlocationpin: "3.2m",
                                            producttype:"Auto",
                                            productspeed:"10 KM",
                                            producttank:"Petrol",
                                            productsystem:"Power",
                                            productyear:2018,
                                            productcity:"Washington",
                                            productprice: '$160',
                                            productimg1:Card5   ,
                                            productimg2:Card5   ,
                                            productimg3:Card5  ,
                                            productimg4:Card5  ,
                                            productimg0:Girl6
                                            },
                        
                                            {
                                                category: "Tesla",
                                                productonimg:"Tesla",
                                                productname: "Tesla Camry SE 350",
                                                productviews: "(4.0) 138 Reviews",
                                                productlocationpin: "3.2m",
                                                producttype:"Auto",
                                                productspeed:"10 KM",
                                                producttank:"Petrol",
                                                productsystem:"Power",
                                                productyear:2018,
                                                productcity:"Washington",
                                                productprice: '$160',
                                                productimg1:ToyoTablue1  ,
                                                productimg2:ToyoTablue2   ,
                                                productimg3:ToyoTablue3  ,
                                                productimg4:ToyoTablue4 ,
                                                productimg0:Girl1
                                                },
                                                 {
                                                    category: "Tesla",
                                                    productonimg:"Tesla",
                                                    productname: "Tesla Camry SE 350",
                                                    productviews: "(4.0) 138 Reviews",
                                                    productlocationpin: "3.2m",
                                                    producttype:"Auto",
                                                    productspeed:"10 KM",
                                                    producttank:"Petrol",
                                                    productsystem:"Power",
                                                    productyear:2018,
                                                    productcity:"Washington",
                                                    productprice: '$160',
                                                    productimg1:Ford1   ,
                                                    productimg2:Ford2  ,
                                                    productimg3:Ford3  ,
                                                    productimg4:Ford4  ,
                                                    productimg0:Girl6
                                                    },
                                                     {
                                                        category: "Tesla",
                                                        productonimg:"Tesla",
                                                        productname: "Tesla Camry SE 350",
                                                        productviews: "(4.0) 138 Reviews",
                                                        productlocationpin: "3.2m",
                                                        producttype:"Auto",
                                                        productspeed:"10 KM",
                                                        producttank:"Petrol",
                                                        productsystem:"Power",
                                                        productyear:2018,
                                                        productcity:"Washington",
                                                        productprice: '$160',
                                                        productimg1: Chevrolet2    ,
                                                        productimg2: Chevrolet1  ,
                                                        productimg3: Chevrolet3  ,
                                                        productimg4: Chevrolet4  ,
                                                        productimg0:Girl6
                                                        }                                  
]
export default Productdata